export const icons = new webix.DataCollection({
	data: [
		{ id:1, value:"Close", icon:"close"},
		{ id:2, value:"User", icon:"user"},
		{ id:3, value:"Folder", icon:"folder"},
		{ id:4, value:"Angle down", icon:"angle-down"},
		{ id:5, value:"Angle left", icon:"angle-left"},
		{ id:6, value:"Angle right", icon:"angle-right"},
		{ id:7, value:"Angle up", icon:"angle-up"},
		{ id:8, value:"Angle double right", icon:"angle-double-right"},
		{ id:9, value:"Angle double left", icon:"angle-double-left"},
		{ id:10, value:"Clock", icon:"clock"},
		{ id:11, value:"Calendar", icon:"calendar"},
		{ id:12, value:"Search", icon:"search"},
		{ id:13, value:"Dots", icon:"dots"},
		{ id:14, value:"Checkbox marked", icon:"checkbox-marked"},
		{ id:15, value:"Checkbox blank", icon:"checkbox-blank"},
		{ id:16, value:"Trash", icon:"trash"},
		{ id:17, value:"Pencil", icon:"pencil"},
		{ id:18, value:"Eye", icon:"eye"},
		{ id:19, value:"Eye slash", icon:"eye-slash"},
		{ id:20, value:"Columns", icon:"columns"},
		{ id:21, value:"Drag", icon:"check"},
		{ id:22, value:"Underline", icon:"underline"},
		{ id:23, value:"Bold", icon:"bold"},
		{ id:24, value:"Italic", icon:"italic"},
		{ id:25, value:"Sync", icon:"sync"},
		{ id:26, value:"Plus square", icon:"plus-square"},
		{ id:27, value:"Minus square", icon:"minus-square"},
		{ id:28, value:"Menu down", icon:"menu-down"},
		{ id:29, value:"Menu right", icon:"menu-right"},
		{ id:30, value:"Menu left", icon:"menu-left"},
		{ id:31, value:"Folder open", icon:"folder-open"},
		{ id:32, value:"File", icon:"file"},
		{ id:33, value:"Close circle", icon:"close-circle"},
		{ id:34, value:"Alert", icon:"alert"},
		{ id:35, value:"Radiobox blank", icon:"radiobox-blank"},
		{ id:36, value:"Radiobox marked", icon:"radiobox-marked"},
		{ id:37, value:"Angle double down", icon:"angle-double-down"},
		{ id:38, value:"Angle double up", icon:"angle-double-up"},
		{ id:39, value:"Plus circle", icon:"plus-circle"},
		{ id:40, value:"Minus circle", icon:"minus-circle"},
		{ id:41, value:"Plus", icon:"plus"},
		{ id:42, value:"Minus", icon:"minus"},
		{ id:43, value:"Download", icon:"download"}
	]
});